window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "secondary-container": "#454747",
        background: "#ffffff",
        "primary-fixed": "#5d5f5f",
        "primary-container": "#131313",
        "on-tertiary-fixed-variant": "#e4e2e1",
        "inverse-on-surface": "#313030",
        "on-primary-container": "#ffffff",
        "surface-container-low": "#f5f5f5",
        "surface-container": "#eeeeee",
        tertiary: "#e4e2e1",
        secondary: "#c6c6c6",
        error: "#ff5449",
        "on-surface": "#131313",
        "surface-container-highest": "#e0e0e0",
        "inverse-surface": "#131313",
        surface: "#ffffff",
        "outline-variant": "#e0e0e0",
        "on-error": "#ffffff",
        "surface-variant": "#eeeeee",
        outline: "#919191",
        "on-primary": "#ffffff",
        "on-background": "#131313",
        "surface-bright": "#ffffff",
        "on-error-container": "#410002",
        primary: "#131313",
        "on-tertiary-container": "#000000",
        "surface-tint": "#131313",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ababab",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#474747",
        "surface-container-high": "#e8e8e8",
        "tertiary-container": "#929090",
        "on-secondary-fixed-variant": "#3a3c3c",
        "on-surface-variant": "#454747",
        "surface-dim": "#f5f5f5",
        "tertiary-fixed": "#5f5e5e",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#131313",
        "inverse-primary": "#ffffff",
        "on-secondary-fixed": "#131313",
        "on-primary-fixed-variant": "#454747",
        "secondary-fixed": "#c6c6c6",
        "primary-fixed-dim": "#454747",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        accent: ["Bormiolo", "cursive"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
